# Generated by Django 5.2.1 on 2025-06-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresstype', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('email', models.TextField()),
                ('deliveryaddress', models.TextField()),
            ],
        ),
    ]
